### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 117: invalid continuation byte

### ISSUE THREAD

**Issue by jan-sopi** [netharuM/srt-subtitle-time-fix#1]
trying to delay some subtitles in portuguese using the command
`srt-stf -f sub1.srt -t 00:00:07,080 -o sub2.srt`
but I get the following error
```
Traceback (most recent call last):
  File "/usr/bin/srt-stf", line 49, in <module>
    main(args)
  File "/usr/bin/srt-stf", line 14, in main
    srt_file_obj.parse_from_str(srt_file.read())
                                ^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xea in position 117: invalid continuation byte
```
got the subtitles from opensubtitles https://www.opensubtitles.org/en/subtitleserve/sub/7274137 and simply renamed them to sub1.srt

any clue on what's going on?

**Comment by netharuM** [comment]
can you provide the subtitle file so I can reproduce the error

**Comment by netharuM** [comment]
This issue occurs when the subtitle file you are using is not encoded with `utf-8`.
In the latest version, there is an argument to specify a custom encoding like `latin-1`

`latin-1` works fine with the subtitle file you have provided
Simple add the argument `-e latin-1` to the command

Example:
```
srt-stf -f sub1.srt -t 00:00:07,080 -o sub2.srt -e latin-1
```
